IMAGE_FILENAME = 'RandomizedBackground.jpg'
IMAGE_URL = 'https://unsplash.com/new'
IMAGE_XPATH_FORMAT = '//*[@id=\"gridMulti\"]//div[@data-test=\"photo-component\"]/div/a/img/@src'
IMAGE_START_VALUE = ''
IMAGE_END_VALUE = '?'
