IMAGE_FILENAME = 'RandomizedBackground.jpg'
IMAGE_URL = 'https://unsplash.com/new'
IMAGE_XPATH_FORMAT = '//img[contains(@src, "https://images.unsplash.com/photo-")]/@src'
IMAGE_START_VALUE = ''
IMAGE_END_VALUE = '?'
