IMAGE_FILENAME = 'RandomizedBackground.jpg'
IMAGE_URL = 'https://unsplash.com/new'
IMAGE_XPATH_FORMAT = '//*[@id=\"gridMulti\"]//a[@class=\"_1hz5D\"]/@style'
IMAGE_START_VALUE = 'background-image:url('
IMAGE_END_VALUE = '?'
